# ──────
# Global
# ──────
colorscheme mygruvbox
# colorscheme solarized-light

set-option global startup_info_version -1
set-option -add global autoinfo normal # Show clippy helper
set-option global matching_pairs ( ) { } [ ] < > “ ” ‘ ’ « » ‹ ›

add-highlighter global/match_brackets show-matching
add-highlighter global/ number-lines -hlcursor -relative -separator ' '

source "%val{config}/local/completion.kak"
source "%val{config}/local/smarttab.kak"

# ────────────────────
# Linting & formatting
# ────────────────────
source "%val{config}/local/formatters.kak"
source "%val{config}/local/linters.kak"

hook global BufCreate .* %{
    editorconfig-load
    autoconfigtab
}

# ──────────────
# Existing modes
# ──────────────
source "%val{config}/local/normal_mode.kak"
source "%val{config}/local/insert_mode.kak"
source "%val{config}/local/user_mode.kak"
source "%val{config}/local/goto-file.kak"

# ────────────
# Custom modes
# ────────────
source "%val{config}/local/multiple-selection.kak"
source "%val{config}/local/files_mode.kak"
source "%val{config}/local/lsp.kak"
source "%val{config}/local/mirror.kak"
source "%val{config}/copied/kakoune-mark.kak"

#
# Playground
#

define-command open_buffer_picker %{
  prompt open: -menu -buffer-completion %{
    buffer -- %val{text}
  }
}

define-command kitty-terminal-window -params 1.. -docstring '
kitty-terminal-window <program> [<arguments>]: create a new terminal as a kitty window
The program passed as argument will be executed in the new terminal' \
%{
    nop %sh{
        match=""
        if [ -n "$kak_client_env_KITTY_WINDOW_ID" ]; then
            match="--match=window_id:$kak_client_env_KITTY_WINDOW_ID"
        fi

        listen=""
        if [ -n "$kak_client_env_KITTY_LISTEN_ON" ]; then
            listen="--to=$kak_client_env_KITTY_LISTEN_ON"
        fi

        kitty @ $listen launch --no-response --type="$kak_opt_kitty_window_type" --cwd="$PWD" $match "$@"
    }
}
complete-command kitty-terminal-window shell

define-command new-client %{
  kitty-terminal kak -c %val{session} %val{buffile}
}

source "%val{config}/local/playground.kak"

hook global WinSetOption filetype=.* %{
  add-highlighter window/ column 81 default,rgb:ff0000
}
